//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumCalcs
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefParams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefParams()
        {
            this.SL_CalcPars = new HashSet<SL_CalcPars>();
        }
    
        public int idDefParam { get; set; }
        public int idDictItem { get; set; }
        public string nameParam { get; set; }
        public string codeParam { get; set; }
        public string sortParam { get; set; }
        public string unitParam { get; set; }
        public string valuesParam { get; set; }
    
        public virtual Diction Diction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SL_CalcPars> SL_CalcPars { get; set; }
    }
}
