//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumCalcs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShumCalcs_DBEntities : DbContext
    {
        public ShumCalcs_DBEntities()
            : base("name=ShumCalcs_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DefParams> DefParams { get; set; }
        public virtual DbSet<Diction> Diction { get; set; }
        public virtual DbSet<SL_CalcPars> SL_CalcPars { get; set; }
        public virtual DbSet<SL_Calcs> SL_Calcs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
