//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumCalcs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_Calcs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SL_Calcs()
        {
            this.SL_CalcPars = new HashSet<SL_CalcPars>();
            this.Children = new HashSet<SL_Calcs>();
        }
    
        public int idCalcItem { get; set; }
        public string nameCalcItem { get; set; }
        public int idDictItem { get; set; }
        public Nullable<int> idParentCalcItem { get; set; }
    
        public virtual Diction Diction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SL_CalcPars> SL_CalcPars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SL_Calcs> Children { get; set; }
        public virtual SL_Calcs Father { get; set; }
    }
}
