//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumCalcs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_CalcPars
    {
        public int idCalc_par { get; set; }
        public int idCalcItem { get; set; }
        public int idDefParam { get; set; }
        public string valueCalc_par { get; set; }
    
        public virtual DefParams DefParams { get; set; }
        public virtual SL_Calcs SL_Calcs { get; set; }
    }
}
